### ISSUE TITLE
Score comparison

### ISSUE THREAD

**Issue by alecuba16** [mbq/praznik#14]
Hello

I'm open an issue about if it is possible to compare score at each selection output.

Let me explain it with an example. I create the following variables and structure for testing purposes:

> change<-c(rep(0,10),rep(1,10))
> no_change<-c(rep(1,20))
> random<-runif(20)
> Y<-as.factor(c(rep(0,10),rep(1,10)))
> X<-data.frame(change=change,no_change=no_change,random=random)
> 
> praznik::DISR(X,Y,k=3)

The Output  is:

> $selection
>    change no_change    random 
>         1         2         3 
> 
> $score
>      change no_change    random 
> 0.6931472 1.0000000 0.4659597 

Well I know that I had fixed the number of the selection to K=3 elements, and they are selected in order 1,2,3. But I would like to know a way to manage the number of selected items based on the score and fix K=ncol(X).

As in the previous example, the score is not growing or decreasing based on the selection order. So I cannot compare based on this criteria.

There is a way to compare the scores? It is a bug? 

Thanks!

**Comment by mbq** [comment]
The result is certainly ok; first, it selects change based on its MI with Y, which is log(2)=.693. Than, it checks mi(X,change;Y)/H(X,change,Y), which is 1 for no_change and somewhat less for random since it has a larger entropy part. Finally, it also selects random, as its score is positive due to the fact that it is once mixed with very informative change and has some small, spurious information on its own.

Going back to the topic, in case of information filters the scores are somewhat secondary output of a limited use -- their main output it a ranking of features. From what I have read, `k` is rather optimised via classifier accuracy than with any score threshold.

Because of that, praznik has `*Scores` functions which can be used to produce something somewhat more useful.
This code, for instance, calculates average CMI of X and Y given some random other attribute, hence should theoretically make values proportional to a random forest importance, yet with very shallow trees (of a depth 2):

```r
rowMeans(replicate(50,cmiScores(X,Y,X[,sample(ncol(X),1)])))
```
