### ISSUE TITLE
Value of SET_STRING_ELT() must be a 'CHARSXP' not a 'character'

### ISSUE THREAD

**Issue by smilesun** [mbq/praznik#9]
reproducible code
```
library(OpenML)
library(mlr)
library(praznik)
Bioresponse = getOMLDataSet(4134)
task = convertOMLDataSetToMlr(Bioresponse)
df = getTaskData(task, target.extra = TRUE)
X = df$data
Y = df$target
praznik::MIM(X= X, Y = Y, k = ncol(X))
```
with some debugging, I found out the problem lies in 
` Ans=finishAns(ke,Ans,X);
` 
of the mim.h file

in `finishAns`, the problem occurs at line 143 of shared.h
`SET_STRING_ELT(An,e,STRING_ELT(Xn,idx[e]-1));`

**Comment by smilesun** [comment]
but I can not really find out more since a lot of values have the "optimized out" property

**Comment by smilesun** [comment]
@mbq , do you have some idea on this?

**Comment by mbq** [comment]
Thank you for the report -- and please excuse my late replay, I missed the original notification.

It seems that there is a problem due to MI-zero features; when you set k to 941 it works well, for 942 it reports one feature of zero MI (which is also wrong), later it tries to pull name of a feature -1 (which is default and should not happen), which causes the error you observe.
Other algos work, so this is likely a bug in the partial sorter; I will check this out.

The result of the fixed code would be exactly like for `praznik::MIM(X= X, Y = Y, k = 941)`, though.

**Comment by mbq** [comment]
Even shorter reproduction:
```r
MIM(data.frame(a=rep(1,150),b=rep(1,150)),iris$Species,2)
```

**Comment by mbq** [comment]
Solved in https://github.com/mbq/praznik/tree/issue9

**Comment by mbq** [comment]
Fixed on CRAN; again, thanks for reporting and sorry for the delay.

**Comment by mbq** [comment]
As for bioresponse data, you can now use `miScores(X,Y)` to just get all MI scores of all features. 
Still, bioresponse is somewhat a tricky dataset for praznik -- there are a number of obviously categorical features but all are represented as numerics normalised to 0-1, which triggers praznik cutting heuristic in places it makes more damage than good.

Hence, to get something meaningful, you should think of fixing the data first; this code for instance factorises all features which have less than 11 different values:

```r
apply(X,2,function(x) length(unique(x)))->nl
for(e in which(nl<=10)) X[,e]<-factor(X[,e])
```
